services:
  ui:
    build:
      context: .
    ports:
      - '4200:4200'
    volumes:
      - ./src:/barber-shop-ui/src
    command: ng serve --host 0.0.0.0 --disable-host-check
    networks:
      - barber-shop-net

networks:
  barber-shop-net:
    name: barber-shop-net
    external: true
